### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by Kaitou-3D** [Serechops/Jizzarr#16]
Branch: Main
OS: Ubuntu Linux (20.04.6 LTS)
Python version: 3.9.20 (venv) (also tried with 3.12, same result)

Trying to build the project, and I run head first into a problem on launch.
Error:
```
poetry run python app.py
Traceback (most recent call last):
  File "/mnt/sdc1/code projects/Jizzarr/app.py", line 19, in <module>
    import pystray
  File "/mnt/sdc1/code projects/Jizzarr/.venv/lib/python3.9/site-packages/pystray/__init__.py", line 64, in <module>
    Icon = backend().Icon
  File "/mnt/sdc1/code projects/Jizzarr/.venv/lib/python3.9/site-packages/pystray/__init__.py", line 56, in backend
    return candidate()
  File "/mnt/sdc1/code projects/Jizzarr/.venv/lib/python3.9/site-packages/pystray/__init__.py", line 36, in xorg
    from . import _xorg as backend; return backend
  File "/mnt/sdc1/code projects/Jizzarr/.venv/lib/python3.9/site-packages/pystray/_xorg.py", line 36, in <module>
    display = Xlib.display.Display()
  File "/mnt/sdc1/code projects/Jizzarr/.venv/lib/python3.9/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/mnt/sdc1/code projects/Jizzarr/.venv/lib/python3.9/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/mnt/sdc1/code projects/Jizzarr/.venv/lib/python3.9/site-packages/Xlib/protocol/display.py", line 84, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
  File "/mnt/sdc1/code projects/Jizzarr/.venv/lib/python3.9/site-packages/Xlib/support/connect.py", line 73, in get_display
    return mod.get_display(display)
  File "/mnt/sdc1/code projects/Jizzarr/.venv/lib/python3.9/site-packages/Xlib/support/unix_connect.py", line 59, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""
```

**Comment by ferengi82** [comment]
i can't get it to work under linux either, i think the problem is with the systray icon and the automatic browser start.
I have already tried to change the app.py, but I always get more error messages (I just don't know enough about python)

=> it would be great if a function could be implemented that checks whether the program is running under windows or linux and then omits the tray icon, browser start etc..

Maybe even a docker image would be possible?
